In [2]:
import pandas as pd

In [8]:


train = pd.read_csv("../data/train.csv")
test = pd.read_csv("../data/test.csv")
sample = pd.read_csv("../data/sample_submission.csv")

print("train shape: ", train.shape)
print("test shape: ", test.shape)

train shape:  (577347, 12)
test shape:  (247435, 11)

In [4]:
train.head()

,id,alpha,delta,u,g,r,i,z,redshift,spectral_type,galaxy_population,class
0,0,147.734256,16.959273,25.472123,21.895559,20.357926,19.257113,18.621057,0.408982,M,Red_Sequence,GALAXY
1,1,127.988677,32.346716,20.778509,19.087062,17.587208,17.226067,16.786433,0.157976,M,Red_Sequence,GALAXY
2,2,179.792648,35.344843,21.035203,21.079128,21.171840,20.582629,20.557366,2.823770,O/B,Blue_Cloud,QSO
3,3,225.818295,48.569421,23.305056,21.050736,19.017754,18.365658,17.914952,0.536099,M,Red_Sequence,GALAXY
4,4,141.836135,19.342852,21.703158,19.471680,18.234449,17.899447,17.616185,0.555761,M,Red_Sequence,GALAXY

In [7]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 577347 entries, 0 to 577346
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 577347 non-null  int64
 1   alpha              577347 non-null  float64
 2   delta              577347 non-null  float64
 3   u                  577347 non-null  float64
 4   g                  577347 non-null  float64
 5   r                  577347 non-null  float64
 6   i                  577347 non-null  float64
 7   z                  577347 non-null  float64
 8   redshift           577347 non-null  float64
 9   spectral_type      577347 non-null  str
 10  galaxy_population  577347 non-null  str
 11  class              577347 non-null  str
dtypes: float64(8), int64(1), str(3)
memory usage: 52.9 MB

In [8]:
train.describe()

,id,alpha,delta,u,g,r,i,z,redshift
count,577347.00000,577347.000000,577347.000000,577347.000000,577347.000000,577347.000000,577347.000000,577347.000000,577347.000000
mean,288673.00000,181.616673,21.834654,22.441926,21.007273,19.962811,19.378911,19.041136,0.723135
std,166665.86727,96.242941,18.933570,2.018135,1.795426,1.648964,1.580059,1.584365,0.810070
min,0.00000,0.011684,-17.966988,-0.139225,13.535483,12.579407,11.962781,11.682803,-0.009970
25%,144336.50000,132.161499,2.474097,20.977090,19.865005,18.820671,18.306820,17.973192,0.181052
50%,288673.00000,188.681465,21.484412,22.570222,21.467820,20.431153,19.631642,19.188598,0.497525
75%,433009.50000,231.829693,36.988310,23.869103,22.292715,21.164096,20.608191,20.162111,0.881390
max,577346.00000,359.999810,79.158322,28.253263,27.620208,25.254499,27.910853,26.826867,7.010780

In [9]:
train["class"].value_counts()

class
GALAXY    377480
QSO       117143
STAR       82724
Name: count, dtype: int64

In [10]:
train["spectral_type"].value_counts()

spectral_type
M      303323
A/F    122122
G/K    108546
O/B     43356
Name: count, dtype: int64

In [11]:
train["galaxy_population"].value_counts()

galaxy_population
Red_Sequence    319565
Blue_Cloud      257782
Name: count, dtype: int64

In [12]:
pd.crosstab(train["spectral_type"], train["class"])

class          GALAXY    QSO   STAR
spectral_type
A/F             24240  61514  36368
G/K             61627  20921  25998
M              288023   3889  11411
O/B              3590  30819   8947

In [13]:
pd.crosstab(train["galaxy_population"], train["class"])

class              GALAXY     QSO   STAR
galaxy_population
Blue_Cloud          88962  108274  60546
Red_Sequence       288518    8869  22178

In [11]:
from catboost import CatBoostClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import balanced_accuracy_score
import numpy as np

In [9]:
X = train.drop(columns=["id", "class"])
y = train["class"]

In [16]:
cat_features = ["spectral_type", "galaxy_population"]

In [17]:
skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

scores = []

In [18]:
for train_idx, valid_idx in skf.split(X, y):

    X_train = X.iloc[train_idx]
    X_valid = X.iloc[valid_idx]

    y_train = y.iloc[train_idx]
    y_valid = y.iloc[valid_idx]

    model = CatBoostClassifier(
        iterations=500,
        learning_rate=0.1,
        depth=6,
        verbose=0
    )

    model.fit(
        X_train,
        y_train,
        cat_features=cat_features
    )

    preds = model.predict(X_valid)

    score = balanced_accuracy_score(
        y_valid,
        preds
    )

    scores.append(score)

    print(score)

0.9463923117967173
0.9485192443437427
0.9482826712058223
0.9472934018201533
0.9467292033201962

In [19]:
print("Mean CV Score:", np.mean(scores))

Mean CV Score: 0.9474433664973263

#### Train on the full dataset:

In [27]:
model = CatBoostClassifier(
    iterations=500,
    learning_rate=0.1,
    depth=6,
    verbose=1
)

model.fit(
    X,
    y,
    cat_features=["spectral_type", "galaxy_population"]
)

0:	learn: 0.9478498	total: 578ms	remaining: 4m 48s
1:	learn: 0.8349083	total: 993ms	remaining: 4m 7s
2:	learn: 0.7453989	total: 1.26s	remaining: 3m 28s
3:	learn: 0.6726046	total: 1.56s	remaining: 3m 14s
4:	learn: 0.6128649	total: 1.85s	remaining: 3m 3s
5:	learn: 0.5616140	total: 2.13s	remaining: 2m 55s
6:	learn: 0.5178888	total: 2.4s	remaining: 2m 49s
7:	learn: 0.4804221	total: 2.71s	remaining: 2m 46s
8:	learn: 0.4472268	total: 3.03s	remaining: 2m 45s
9:	learn: 0.4192323	total: 3.33s	remaining: 2m 43s
10:	learn: 0.3939768	total: 3.63s	remaining: 2m 41s
11:	learn: 0.3720003	total: 3.91s	remaining: 2m 38s
12:	learn: 0.3512100	total: 4.22s	remaining: 2m 38s
13:	learn: 0.3325782	total: 4.48s	remaining: 2m 35s
14:	learn: 0.3159990	total: 4.75s	remaining: 2m 33s
15:	learn: 0.3013850	total: 5.03s	remaining: 2m 32s
16:	learn: 0.2887640	total: 5.28s	remaining: 2m 29s
17:	learn: 0.2752255	total: 5.53s	remaining: 2m 28s
18:	learn: 0.2643134	total: 5.8s	remaining: 2m 26s
19:	learn: 0.2542665	total: 6.07s	remaining: 2m 25s
20:	learn: 0.2461584	total: 6.33s	remaining: 2m 24s
21:	learn: 0.2381580	total: 6.6s	remaining: 2m 23s
22:	learn: 0.2310627	total: 6.87s	remaining: 2m 22s
23:	learn: 0.2259341	total: 7.17s	remaining: 2m 22s
24:	learn: 0.2196486	total: 7.43s	remaining: 2m 21s
25:	learn: 0.2145533	total: 7.71s	remaining: 2m 20s
26:	learn: 0.2094524	total: 7.98s	remaining: 2m 19s
27:	learn: 0.2050331	total: 8.24s	remaining: 2m 18s
28:	learn: 0.2010805	total: 8.52s	remaining: 2m 18s
29:	learn: 0.1978609	total: 8.78s	remaining: 2m 17s
30:	learn: 0.1940469	total: 9.04s	remaining: 2m 16s
31:	learn: 0.1906059	total: 9.31s	remaining: 2m 16s
32:	learn: 0.1875805	total: 9.59s	remaining: 2m 15s
33:	learn: 0.1845181	total: 9.86s	remaining: 2m 15s
34:	learn: 0.1815299	total: 10.1s	remaining: 2m 14s
35:	learn: 0.1796371	total: 10.4s	remaining: 2m 14s
36:	learn: 0.1777001	total: 10.6s	remaining: 2m 13s
37:	learn: 0.1752849	total: 10.9s	remaining: 2m 12s
38:	learn: 0.1732542	total: 11.2s	remaining: 2m 12s
39:	learn: 0.1714761	total: 11.4s	remaining: 2m 11s
40:	learn: 0.1700362	total: 11.7s	remaining: 2m 11s
41:	learn: 0.1684072	total: 12s	remaining: 2m 10s
42:	learn: 0.1664839	total: 12.3s	remaining: 2m 10s
43:	learn: 0.1653603	total: 12.6s	remaining: 2m 10s
44:	learn: 0.1642749	total: 12.8s	remaining: 2m 9s
45:	learn: 0.1624593	total: 13.1s	remaining: 2m 9s
46:	learn: 0.1608687	total: 13.4s	remaining: 2m 8s
47:	learn: 0.1597943	total: 13.7s	remaining: 2m 8s
48:	learn: 0.1589558	total: 13.9s	remaining: 2m 8s
49:	learn: 0.1582265	total: 14.2s	remaining: 2m 7s
50:	learn: 0.1574862	total: 14.4s	remaining: 2m 7s
51:	learn: 0.1566934	total: 14.7s	remaining: 2m 6s
52:	learn: 0.1560462	total: 15s	remaining: 2m 6s
53:	learn: 0.1554625	total: 15.2s	remaining: 2m 5s
54:	learn: 0.1545549	total: 15.5s	remaining: 2m 5s
55:	learn: 0.1535502	total: 15.8s	remaining: 2m 4s
56:	learn: 0.1531061	total: 16s	remaining: 2m 4s
57:	learn: 0.1522887	total: 16.3s	remaining: 2m 3s
58:	learn: 0.1514781	total: 16.5s	remaining: 2m 3s
59:	learn: 0.1508445	total: 16.8s	remaining: 2m 3s
60:	learn: 0.1498398	total: 17.1s	remaining: 2m 2s
61:	learn: 0.1491891	total: 17.4s	remaining: 2m 2s
62:	learn: 0.1486704	total: 17.6s	remaining: 2m 2s
63:	learn: 0.1479085	total: 17.9s	remaining: 2m 1s
64:	learn: 0.1473838	total: 18.1s	remaining: 2m 1s
65:	learn: 0.1467200	total: 18.4s	remaining: 2m
66:	learn: 0.1462907	total: 18.6s	remaining: 2m
67:	learn: 0.1459297	total: 18.9s	remaining: 2m
68:	learn: 0.1455095	total: 19.2s	remaining: 1m 59s
69:	learn: 0.1446516	total: 19.5s	remaining: 1m 59s
70:	learn: 0.1441562	total: 19.8s	remaining: 1m 59s
71:	learn: 0.1436214	total: 20s	remaining: 1m 59s
72:	learn: 0.1432493	total: 20.3s	remaining: 1m 58s
73:	learn: 0.1427245	total: 20.6s	remaining: 1m 58s
74:	learn: 0.1423859	total: 20.9s	remaining: 1m 58s
75:	learn: 0.1420583	total: 21.2s	remaining: 1m 58s
76:	learn: 0.1412875	total: 21.5s	remaining: 1m 57s
77:	learn: 0.1408019	total: 21.8s	remaining: 1m 57s
78:	learn: 0.1401690	total: 22s	remaining: 1m 57s
79:	learn: 0.1398805	total: 22.3s	remaining: 1m 57s
80:	learn: 0.1392941	total: 22.6s	remaining: 1m 56s
81:	learn: 0.1388811	total: 22.9s	remaining: 1m 56s
82:	learn: 0.1384255	total: 23.1s	remaining: 1m 56s
83:	learn: 0.1382228	total: 23.4s	remaining: 1m 55s
84:	learn: 0.1378874	total: 23.6s	remaining: 1m 55s
85:	learn: 0.1375747	total: 23.9s	remaining: 1m 55s
86:	learn: 0.1373697	total: 24.1s	remaining: 1m 54s
87:	learn: 0.1370334	total: 24.4s	remaining: 1m 54s
88:	learn: 0.1367569	total: 24.7s	remaining: 1m 54s
89:	learn: 0.1364152	total: 25s	remaining: 1m 53s
90:	learn: 0.1361581	total: 25.2s	remaining: 1m 53s
91:	learn: 0.1356418	total: 25.5s	remaining: 1m 52s
92:	learn: 0.1352851	total: 25.8s	remaining: 1m 52s
93:	learn: 0.1350905	total: 26s	remaining: 1m 52s
94:	learn: 0.1346043	total: 26.3s	remaining: 1m 52s
95:	learn: 0.1342632	total: 26.6s	remaining: 1m 51s
96:	learn: 0.1337264	total: 26.9s	remaining: 1m 51s
97:	learn: 0.1333741	total: 27.2s	remaining: 1m 51s
98:	learn: 0.1331408	total: 27.5s	remaining: 1m 51s
99:	learn: 0.1326816	total: 27.8s	remaining: 1m 51s
100:	learn: 0.1323722	total: 28s	remaining: 1m 50s
101:	learn: 0.1322910	total: 28.2s	remaining: 1m 50s
102:	learn: 0.1319331	total: 28.5s	remaining: 1m 49s
103:	learn: 0.1316639	total: 28.7s	remaining: 1m 49s
104:	learn: 0.1315609	total: 29s	remaining: 1m 49s
105:	learn: 0.1311817	total: 29.3s	remaining: 1m 48s
106:	learn: 0.1310133	total: 29.5s	remaining: 1m 48s
107:	learn: 0.1308073	total: 29.8s	remaining: 1m 48s
108:	learn: 0.1306594	total: 30.1s	remaining: 1m 47s
109:	learn: 0.1303333	total: 30.3s	remaining: 1m 47s
110:	learn: 0.1300594	total: 30.6s	remaining: 1m 47s
111:	learn: 0.1298777	total: 30.9s	remaining: 1m 46s
112:	learn: 0.1295987	total: 31.1s	remaining: 1m 46s
113:	learn: 0.1293197	total: 31.4s	remaining: 1m 46s
114:	learn: 0.1290890	total: 31.7s	remaining: 1m 46s
115:	learn: 0.1289093	total: 32s	remaining: 1m 45s
116:	learn: 0.1286957	total: 32.2s	remaining: 1m 45s
117:	learn: 0.1283965	total: 32.5s	remaining: 1m 45s
118:	learn: 0.1282551	total: 32.7s	remaining: 1m 44s
119:	learn: 0.1281712	total: 33s	remaining: 1m 44s
120:	learn: 0.1279462	total: 33.4s	remaining: 1m 44s
121:	learn: 0.1277837	total: 33.7s	remaining: 1m 44s
122:	learn: 0.1275867	total: 33.9s	remaining: 1m 44s
123:	learn: 0.1273575	total: 34.2s	remaining: 1m 43s
124:	learn: 0.1269025	total: 34.5s	remaining: 1m 43s
125:	learn: 0.1267440	total: 34.8s	remaining: 1m 43s
126:	learn: 0.1264348	total: 35s	remaining: 1m 42s
127:	learn: 0.1262640	total: 35.3s	remaining: 1m 42s
128:	learn: 0.1261619	total: 35.5s	remaining: 1m 42s
129:	learn: 0.1258781	total: 35.8s	remaining: 1m 41s
130:	learn: 0.1254163	total: 36.1s	remaining: 1m 41s
131:	learn: 0.1252382	total: 36.3s	remaining: 1m 41s
132:	learn: 0.1249482	total: 36.6s	remaining: 1m 41s
133:	learn: 0.1247984	total: 36.9s	remaining: 1m 40s
134:	learn: 0.1246326	total: 37.1s	remaining: 1m 40s
135:	learn: 0.1244753	total: 37.4s	remaining: 1m 40s
136:	learn: 0.1242879	total: 37.7s	remaining: 1m 39s
137:	learn: 0.1240033	total: 37.9s	remaining: 1m 39s
138:	learn: 0.1237636	total: 38.2s	remaining: 1m 39s
139:	learn: 0.1236638	total: 38.5s	remaining: 1m 38s
140:	learn: 0.1234607	total: 38.7s	remaining: 1m 38s
141:	learn: 0.1232863	total: 39s	remaining: 1m 38s
142:	learn: 0.1231564	total: 39.2s	remaining: 1m 37s
143:	learn: 0.1230797	total: 39.5s	remaining: 1m 37s
144:	learn: 0.1228276	total: 39.8s	remaining: 1m 37s
145:	learn: 0.1227408	total: 40.1s	remaining: 1m 37s
146:	learn: 0.1224965	total: 40.3s	remaining: 1m 36s
147:	learn: 0.1224085	total: 40.6s	remaining: 1m 36s
148:	learn: 0.1222751	total: 40.8s	remaining: 1m 36s
149:	learn: 0.1221916	total: 41.1s	remaining: 1m 36s
150:	learn: 0.1220971	total: 41.4s	remaining: 1m 35s
151:	learn: 0.1219923	total: 41.7s	remaining: 1m 35s
152:	learn: 0.1217125	total: 42s	remaining: 1m 35s
153:	learn: 0.1215350	total: 42.3s	remaining: 1m 34s
154:	learn: 0.1214091	total: 42.5s	remaining: 1m 34s
155:	learn: 0.1213353	total: 42.8s	remaining: 1m 34s
156:	learn: 0.1212248	total: 43.1s	remaining: 1m 34s
157:	learn: 0.1211689	total: 43.3s	remaining: 1m 33s
158:	learn: 0.1210704	total: 43.6s	remaining: 1m 33s
159:	learn: 0.1208539	total: 43.9s	remaining: 1m 33s
160:	learn: 0.1207288	total: 44.2s	remaining: 1m 32s
161:	learn: 0.1205859	total: 44.4s	remaining: 1m 32s
162:	learn: 0.1204645	total: 44.7s	remaining: 1m 32s
163:	learn: 0.1203652	total: 45s	remaining: 1m 32s
164:	learn: 0.1202117	total: 45.2s	remaining: 1m 31s
165:	learn: 0.1200338	total: 45.5s	remaining: 1m 31s
166:	learn: 0.1199776	total: 45.7s	remaining: 1m 31s
167:	learn: 0.1197150	total: 46s	remaining: 1m 30s
168:	learn: 0.1195201	total: 46.3s	remaining: 1m 30s
169:	learn: 0.1193025	total: 46.5s	remaining: 1m 30s
170:	learn: 0.1190334	total: 46.8s	remaining: 1m 30s
171:	learn: 0.1188329	total: 47.1s	remaining: 1m 29s
172:	learn: 0.1186295	total: 47.4s	remaining: 1m 29s
173:	learn: 0.1185890	total: 47.6s	remaining: 1m 29s
174:	learn: 0.1184543	total: 47.9s	remaining: 1m 28s
175:	learn: 0.1182651	total: 48.1s	remaining: 1m 28s
176:	learn: 0.1181685	total: 48.4s	remaining: 1m 28s
177:	learn: 0.1179848	total: 48.7s	remaining: 1m 28s
178:	learn: 0.1179533	total: 48.9s	remaining: 1m 27s
179:	learn: 0.1178295	total: 49.2s	remaining: 1m 27s
180:	learn: 0.1177210	total: 49.5s	remaining: 1m 27s
181:	learn: 0.1176413	total: 49.8s	remaining: 1m 26s
182:	learn: 0.1175299	total: 50s	remaining: 1m 26s
183:	learn: 0.1174858	total: 50.3s	remaining: 1m 26s
184:	learn: 0.1173561	total: 50.6s	remaining: 1m 26s
185:	learn: 0.1172389	total: 50.8s	remaining: 1m 25s
186:	learn: 0.1171428	total: 51.1s	remaining: 1m 25s
187:	learn: 0.1170400	total: 51.3s	remaining: 1m 25s
188:	learn: 0.1169870	total: 51.6s	remaining: 1m 24s
189:	learn: 0.1169098	total: 51.9s	remaining: 1m 24s
190:	learn: 0.1168140	total: 52.1s	remaining: 1m 24s
191:	learn: 0.1166300	total: 52.3s	remaining: 1m 23s
192:	learn: 0.1165239	total: 52.6s	remaining: 1m 23s
193:	learn: 0.1164429	total: 52.9s	remaining: 1m 23s
194:	learn: 0.1162689	total: 53.1s	remaining: 1m 23s
195:	learn: 0.1161593	total: 53.4s	remaining: 1m 22s
196:	learn: 0.1161010	total: 53.6s	remaining: 1m 22s
197:	learn: 0.1159795	total: 53.9s	remaining: 1m 22s
198:	learn: 0.1158625	total: 54.1s	remaining: 1m 21s
199:	learn: 0.1156392	total: 54.4s	remaining: 1m 21s
200:	learn: 0.1155236	total: 54.7s	remaining: 1m 21s
201:	learn: 0.1153945	total: 54.9s	remaining: 1m 21s
202:	learn: 0.1151729	total: 55.2s	remaining: 1m 20s
203:	learn: 0.1150772	total: 55.5s	remaining: 1m 20s
204:	learn: 0.1150243	total: 55.7s	remaining: 1m 20s
205:	learn: 0.1148441	total: 56s	remaining: 1m 19s
206:	learn: 0.1147480	total: 56.2s	remaining: 1m 19s
207:	learn: 0.1146511	total: 56.5s	remaining: 1m 19s
208:	learn: 0.1144884	total: 56.8s	remaining: 1m 19s
209:	learn: 0.1142323	total: 57s	remaining: 1m 18s
210:	learn: 0.1141524	total: 57.3s	remaining: 1m 18s
211:	learn: 0.1140178	total: 57.6s	remaining: 1m 18s
212:	learn: 0.1139225	total: 57.8s	remaining: 1m 17s
213:	learn: 0.1138334	total: 58.1s	remaining: 1m 17s
214:	learn: 0.1136738	total: 58.4s	remaining: 1m 17s
215:	learn: 0.1136285	total: 58.6s	remaining: 1m 17s
216:	learn: 0.1134724	total: 58.9s	remaining: 1m 16s
217:	learn: 0.1133701	total: 59.1s	remaining: 1m 16s
218:	learn: 0.1131959	total: 59.4s	remaining: 1m 16s
219:	learn: 0.1131143	total: 59.7s	remaining: 1m 15s
220:	learn: 0.1130093	total: 59.9s	remaining: 1m 15s
221:	learn: 0.1129192	total: 1m	remaining: 1m 15s
222:	learn: 0.1128375	total: 1m	remaining: 1m 15s
223:	learn: 0.1126814	total: 1m	remaining: 1m 14s
224:	learn: 0.1125636	total: 1m	remaining: 1m 14s
225:	learn: 0.1125200	total: 1m 1s	remaining: 1m 14s
226:	learn: 0.1124366	total: 1m 1s	remaining: 1m 13s
227:	learn: 0.1123797	total: 1m 1s	remaining: 1m 13s
228:	learn: 0.1123036	total: 1m 2s	remaining: 1m 13s
229:	learn: 0.1122267	total: 1m 2s	remaining: 1m 13s
230:	learn: 0.1121552	total: 1m 2s	remaining: 1m 12s
231:	learn: 0.1120467	total: 1m 2s	remaining: 1m 12s
232:	learn: 0.1118421	total: 1m 3s	remaining: 1m 12s
233:	learn: 0.1117494	total: 1m 3s	remaining: 1m 11s
234:	learn: 0.1116518	total: 1m 3s	remaining: 1m 11s
235:	learn: 0.1115444	total: 1m 3s	remaining: 1m 11s
236:	learn: 0.1114758	total: 1m 4s	remaining: 1m 11s
237:	learn: 0.1114291	total: 1m 4s	remaining: 1m 10s
238:	learn: 0.1113591	total: 1m 4s	remaining: 1m 10s
239:	learn: 0.1112792	total: 1m 4s	remaining: 1m 10s
240:	learn: 0.1111577	total: 1m 5s	remaining: 1m 10s
241:	learn: 0.1110528	total: 1m 5s	remaining: 1m 9s
242:	learn: 0.1110284	total: 1m 5s	remaining: 1m 9s
243:	learn: 0.1109666	total: 1m 6s	remaining: 1m 9s
244:	learn: 0.1109321	total: 1m 6s	remaining: 1m 9s
245:	learn: 0.1108786	total: 1m 6s	remaining: 1m 8s
246:	learn: 0.1107848	total: 1m 6s	remaining: 1m 8s
247:	learn: 0.1106985	total: 1m 7s	remaining: 1m 8s
248:	learn: 0.1106397	total: 1m 7s	remaining: 1m 7s
249:	learn: 0.1105319	total: 1m 7s	remaining: 1m 7s
250:	learn: 0.1104690	total: 1m 7s	remaining: 1m 7s
251:	learn: 0.1104362	total: 1m 8s	remaining: 1m 7s
252:	learn: 0.1102996	total: 1m 8s	remaining: 1m 6s
253:	learn: 0.1102461	total: 1m 8s	remaining: 1m 6s
254:	learn: 0.1101594	total: 1m 8s	remaining: 1m 6s
255:	learn: 0.1101394	total: 1m 9s	remaining: 1m 5s
256:	learn: 0.1100594	total: 1m 9s	remaining: 1m 5s
257:	learn: 0.1099974	total: 1m 9s	remaining: 1m 5s
258:	learn: 0.1099020	total: 1m 10s	remaining: 1m 5s
259:	learn: 0.1098588	total: 1m 10s	remaining: 1m 4s
260:	learn: 0.1098110	total: 1m 10s	remaining: 1m 4s
261:	learn: 0.1097551	total: 1m 10s	remaining: 1m 4s
262:	learn: 0.1096954	total: 1m 11s	remaining: 1m 4s
263:	learn: 0.1096229	total: 1m 11s	remaining: 1m 3s
264:	learn: 0.1095381	total: 1m 11s	remaining: 1m 3s
265:	learn: 0.1095069	total: 1m 12s	remaining: 1m 3s
266:	learn: 0.1094636	total: 1m 12s	remaining: 1m 3s
267:	learn: 0.1093770	total: 1m 12s	remaining: 1m 2s
268:	learn: 0.1092723	total: 1m 13s	remaining: 1m 2s
269:	learn: 0.1092349	total: 1m 13s	remaining: 1m 2s
270:	learn: 0.1091964	total: 1m 13s	remaining: 1m 2s
271:	learn: 0.1091417	total: 1m 13s	remaining: 1m 1s
272:	learn: 0.1090195	total: 1m 14s	remaining: 1m 1s
273:	learn: 0.1088832	total: 1m 14s	remaining: 1m 1s
274:	learn: 0.1088322	total: 1m 14s	remaining: 1m 1s
275:	learn: 0.1087416	total: 1m 14s	remaining: 1m
276:	learn: 0.1086623	total: 1m 15s	remaining: 1m
277:	learn: 0.1085341	total: 1m 15s	remaining: 1m
278:	learn: 0.1085101	total: 1m 15s	remaining: 59.9s
279:	learn: 0.1084747	total: 1m 15s	remaining: 59.6s
280:	learn: 0.1083649	total: 1m 16s	remaining: 59.3s
281:	learn: 0.1083254	total: 1m 16s	remaining: 59s
282:	learn: 0.1083144	total: 1m 16s	remaining: 58.7s
283:	learn: 0.1082167	total: 1m 16s	remaining: 58.5s
284:	learn: 0.1081544	total: 1m 17s	remaining: 58.2s
285:	learn: 0.1081155	total: 1m 17s	remaining: 57.9s
286:	learn: 0.1080634	total: 1m 17s	remaining: 57.6s
287:	learn: 0.1080242	total: 1m 17s	remaining: 57.4s
288:	learn: 0.1079619	total: 1m 18s	remaining: 57.1s
289:	learn: 0.1078842	total: 1m 18s	remaining: 56.8s
290:	learn: 0.1078510	total: 1m 18s	remaining: 56.5s
291:	learn: 0.1078251	total: 1m 18s	remaining: 56.2s
292:	learn: 0.1077455	total: 1m 19s	remaining: 56s
293:	learn: 0.1077107	total: 1m 19s	remaining: 55.7s
294:	learn: 0.1076679	total: 1m 19s	remaining: 55.4s
295:	learn: 0.1076028	total: 1m 20s	remaining: 55.1s
296:	learn: 0.1075795	total: 1m 20s	remaining: 54.9s
297:	learn: 0.1075360	total: 1m 20s	remaining: 54.6s
298:	learn: 0.1074527	total: 1m 20s	remaining: 54.3s
299:	learn: 0.1073587	total: 1m 21s	remaining: 54s
300:	learn: 0.1073315	total: 1m 21s	remaining: 53.8s
301:	learn: 0.1072293	total: 1m 21s	remaining: 53.5s
302:	learn: 0.1072081	total: 1m 21s	remaining: 53.2s
303:	learn: 0.1071062	total: 1m 22s	remaining: 52.9s
304:	learn: 0.1070761	total: 1m 22s	remaining: 52.7s
305:	learn: 0.1070177	total: 1m 22s	remaining: 52.4s
306:	learn: 0.1069461	total: 1m 22s	remaining: 52.1s
307:	learn: 0.1068716	total: 1m 23s	remaining: 51.9s
308:	learn: 0.1068387	total: 1m 23s	remaining: 51.6s
309:	learn: 0.1068115	total: 1m 23s	remaining: 51.3s
310:	learn: 0.1067911	total: 1m 23s	remaining: 51s
311:	learn: 0.1067752	total: 1m 24s	remaining: 50.7s
312:	learn: 0.1066842	total: 1m 24s	remaining: 50.5s
313:	learn: 0.1066474	total: 1m 24s	remaining: 50.2s
314:	learn: 0.1065852	total: 1m 24s	remaining: 49.9s
315:	learn: 0.1065698	total: 1m 25s	remaining: 49.6s
316:	learn: 0.1065211	total: 1m 25s	remaining: 49.4s
317:	learn: 0.1064311	total: 1m 25s	remaining: 49.1s
318:	learn: 0.1063895	total: 1m 26s	remaining: 48.8s
319:	learn: 0.1063091	total: 1m 26s	remaining: 48.6s
320:	learn: 0.1062584	total: 1m 26s	remaining: 48.3s
321:	learn: 0.1062154	total: 1m 26s	remaining: 48s
322:	learn: 0.1061823	total: 1m 27s	remaining: 47.7s
323:	learn: 0.1061589	total: 1m 27s	remaining: 47.5s
324:	learn: 0.1061023	total: 1m 27s	remaining: 47.2s
325:	learn: 0.1060074	total: 1m 27s	remaining: 46.9s
326:	learn: 0.1059777	total: 1m 28s	remaining: 46.6s
327:	learn: 0.1059542	total: 1m 28s	remaining: 46.4s
328:	learn: 0.1059034	total: 1m 28s	remaining: 46.1s
329:	learn: 0.1058808	total: 1m 28s	remaining: 45.8s
330:	learn: 0.1058527	total: 1m 29s	remaining: 45.5s
331:	learn: 0.1058165	total: 1m 29s	remaining: 45.3s
332:	learn: 0.1057437	total: 1m 29s	remaining: 45s
333:	learn: 0.1057166	total: 1m 30s	remaining: 44.7s
334:	learn: 0.1056271	total: 1m 30s	remaining: 44.5s
335:	learn: 0.1055383	total: 1m 30s	remaining: 44.2s
336:	learn: 0.1055154	total: 1m 30s	remaining: 43.9s
337:	learn: 0.1054426	total: 1m 31s	remaining: 43.7s
338:	learn: 0.1053773	total: 1m 31s	remaining: 43.4s
339:	learn: 0.1053615	total: 1m 31s	remaining: 43.1s
340:	learn: 0.1052812	total: 1m 31s	remaining: 42.9s
341:	learn: 0.1052540	total: 1m 32s	remaining: 42.6s
342:	learn: 0.1051900	total: 1m 32s	remaining: 42.3s
343:	learn: 0.1051231	total: 1m 32s	remaining: 42s
344:	learn: 0.1050685	total: 1m 32s	remaining: 41.8s
345:	learn: 0.1050347	total: 1m 33s	remaining: 41.5s
346:	learn: 0.1050147	total: 1m 33s	remaining: 41.2s
347:	learn: 0.1049904	total: 1m 33s	remaining: 40.9s
348:	learn: 0.1049674	total: 1m 33s	remaining: 40.7s
349:	learn: 0.1049110	total: 1m 34s	remaining: 40.4s
350:	learn: 0.1048696	total: 1m 34s	remaining: 40.1s
351:	learn: 0.1048236	total: 1m 34s	remaining: 39.8s
352:	learn: 0.1047843	total: 1m 35s	remaining: 39.6s
353:	learn: 0.1047463	total: 1m 35s	remaining: 39.3s
354:	learn: 0.1047219	total: 1m 35s	remaining: 39s
355:	learn: 0.1046873	total: 1m 35s	remaining: 38.8s
356:	learn: 0.1046531	total: 1m 36s	remaining: 38.5s
357:	learn: 0.1045650	total: 1m 36s	remaining: 38.2s
358:	learn: 0.1045408	total: 1m 36s	remaining: 37.9s
359:	learn: 0.1045166	total: 1m 36s	remaining: 37.7s
360:	learn: 0.1044579	total: 1m 37s	remaining: 37.4s
361:	learn: 0.1044138	total: 1m 37s	remaining: 37.1s
362:	learn: 0.1043463	total: 1m 37s	remaining: 36.8s
363:	learn: 0.1043091	total: 1m 37s	remaining: 36.6s
364:	learn: 0.1042768	total: 1m 38s	remaining: 36.3s
365:	learn: 0.1042503	total: 1m 38s	remaining: 36s
366:	learn: 0.1042147	total: 1m 38s	remaining: 35.8s
367:	learn: 0.1041803	total: 1m 38s	remaining: 35.5s
368:	learn: 0.1041601	total: 1m 39s	remaining: 35.2s
369:	learn: 0.1041095	total: 1m 39s	remaining: 34.9s
370:	learn: 0.1040324	total: 1m 39s	remaining: 34.7s
371:	learn: 0.1040044	total: 1m 39s	remaining: 34.4s
372:	learn: 0.1039613	total: 1m 40s	remaining: 34.1s
373:	learn: 0.1039399	total: 1m 40s	remaining: 33.9s
374:	learn: 0.1039248	total: 1m 40s	remaining: 33.6s
375:	learn: 0.1038827	total: 1m 40s	remaining: 33.3s
376:	learn: 0.1038733	total: 1m 41s	remaining: 33s
377:	learn: 0.1038060	total: 1m 41s	remaining: 32.8s
378:	learn: 0.1037855	total: 1m 41s	remaining: 32.5s
379:	learn: 0.1037684	total: 1m 42s	remaining: 32.2s
380:	learn: 0.1037242	total: 1m 42s	remaining: 31.9s

CatBoostClassifier(depth=6, iterations=500, learning_rate=0.1, verbose=1)

In [28]:
model.save_model("../models/catboost_v1.cbm")

In [29]:
X_test = test.drop(columns=["id"])

preds = model.predict(X_test)

In [30]:
submission = pd.DataFrame({
    "id": test["id"],
    "class": preds.flatten()
})

submission.to_csv(
    "../submissions/submission_v1.csv",
    index=False
)

In [5]:
from catboost import CatBoostClassifier
model = CatBoostClassifier()
model.load_model("../models/catboost_v1.cbm")

CatBoostClassifier(depth=6, iterations=500, learning_rate=0.1, loss_function='MultiClass', verbose=1)

In [31]:
submission.head()

       id   class
0  577347  GALAXY
1  577348  GALAXY
2  577349  GALAXY
3  577350    STAR
4  577351  GALAXY

### Experiment v2

In [10]:
feature_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.get_feature_importance()
})

feature_importance.sort_values(
    by="Importance",
    ascending=False
)

             Feature  Importance
7           redshift   34.565155
6                  z   12.282269
2                  u    9.544425
3                  g    9.195414
0              alpha    8.375548
1              delta    6.393684
8      spectral_type    6.167067
9  galaxy_population    4.873580
5                  i    4.432424
4                  r    4.170433

# ==================================
# Experiment V2
# Stronger CatBoost
# ==================================

In [12]:
skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

scores = []

for train_idx, valid_idx in skf.split(X, y):

    X_train = X.iloc[train_idx]
    X_valid = X.iloc[valid_idx]

    y_train = y.iloc[train_idx]
    y_valid = y.iloc[valid_idx]

    model = CatBoostClassifier(
        iterations=1000,
        learning_rate=0.05,
        depth=8,
        verbose=1
    )

    model.fit(
        X_train,
        y_train,
        cat_features=["spectral_type", "galaxy_population"]
    )

    preds = model.predict(X_valid)

    score = balanced_accuracy_score(y_valid, preds)

    scores.append(score)

    print(f"Fold Score: {score:.6f}")

print("\nMean CV Score:", np.mean(scores))

0:	learn: 1.0196973	total: 502ms	remaining: 8m 21s
1:	learn: 0.9513594	total: 858ms	remaining: 7m 8s
2:	learn: 0.8909209	total: 1.21s	remaining: 6m 42s
3:	learn: 0.8377900	total: 1.57s	remaining: 6m 30s
4:	learn: 0.7899593	total: 1.91s	remaining: 6m 19s
5:	learn: 0.7469625	total: 2.25s	remaining: 6m 12s
6:	learn: 0.7078803	total: 2.59s	remaining: 6m 7s
7:	learn: 0.6725852	total: 2.94s	remaining: 6m 4s
8:	learn: 0.6403509	total: 3.28s	remaining: 6m 1s
9:	learn: 0.6105671	total: 3.62s	remaining: 5m 58s
10:	learn: 0.5834226	total: 3.97s	remaining: 5m 56s
11:	learn: 0.5582966	total: 4.32s	remaining: 5m 55s
12:	learn: 0.5349597	total: 4.65s	remaining: 5m 53s
13:	learn: 0.5133974	total: 4.99s	remaining: 5m 51s
14:	learn: 0.4928081	total: 5.35s	remaining: 5m 51s
15:	learn: 0.4740191	total: 5.68s	remaining: 5m 49s
16:	learn: 0.4564087	total: 6.03s	remaining: 5m 48s
17:	learn: 0.4398333	total: 6.38s	remaining: 5m 47s
18:	learn: 0.4245064	total: 6.73s	remaining: 5m 47s
19:	learn: 0.4097632	total: 7.09s	remaining: 5m 47s
20:	learn: 0.3963091	total: 7.43s	remaining: 5m 46s
21:	learn: 0.3835633	total: 7.8s	remaining: 5m 46s
22:	learn: 0.3712146	total: 8.15s	remaining: 5m 46s
23:	learn: 0.3590775	total: 8.48s	remaining: 5m 44s
24:	learn: 0.3477661	total: 8.82s	remaining: 5m 44s
25:	learn: 0.3375016	total: 9.16s	remaining: 5m 43s
26:	learn: 0.3276885	total: 9.5s	remaining: 5m 42s
27:	learn: 0.3184443	total: 9.85s	remaining: 5m 41s
28:	learn: 0.3099069	total: 10.2s	remaining: 5m 40s
29:	learn: 0.3016253	total: 10.5s	remaining: 5m 39s
30:	learn: 0.2940191	total: 10.8s	remaining: 5m 38s
31:	learn: 0.2869783	total: 11.1s	remaining: 5m 37s
32:	learn: 0.2804435	total: 11.5s	remaining: 5m 36s
33:	learn: 0.2740414	total: 11.8s	remaining: 5m 35s
34:	learn: 0.2677868	total: 12.1s	remaining: 5m 34s
35:	learn: 0.2619371	total: 12.4s	remaining: 5m 32s
36:	learn: 0.2563652	total: 12.8s	remaining: 5m 32s
37:	learn: 0.2509960	total: 13.1s	remaining: 5m 31s
38:	learn: 0.2460857	total: 13.4s	remaining: 5m 30s
39:	learn: 0.2412821	total: 13.7s	remaining: 5m 29s
40:	learn: 0.2370597	total: 14.1s	remaining: 5m 28s
41:	learn: 0.2330173	total: 14.4s	remaining: 5m 28s
42:	learn: 0.2289817	total: 14.7s	remaining: 5m 27s
43:	learn: 0.2249868	total: 15s	remaining: 5m 26s
44:	learn: 0.2211720	total: 15.3s	remaining: 5m 25s
45:	learn: 0.2176595	total: 15.7s	remaining: 5m 24s
46:	learn: 0.2145114	total: 16s	remaining: 5m 23s
47:	learn: 0.2113227	total: 16.3s	remaining: 5m 22s
48:	learn: 0.2083619	total: 16.6s	remaining: 5m 21s
49:	learn: 0.2058160	total: 16.9s	remaining: 5m 20s
50:	learn: 0.2028441	total: 17.2s	remaining: 5m 20s
51:	learn: 0.2002310	total: 17.5s	remaining: 5m 19s
52:	learn: 0.1974337	total: 17.8s	remaining: 5m 18s
53:	learn: 0.1949016	total: 18.2s	remaining: 5m 18s
54:	learn: 0.1924977	total: 18.5s	remaining: 5m 18s
55:	learn: 0.1902136	total: 18.9s	remaining: 5m 17s
56:	learn: 0.1880587	total: 19.2s	remaining: 5m 17s
57:	learn: 0.1860609	total: 19.5s	remaining: 5m 16s
58:	learn: 0.1839753	total: 19.8s	remaining: 5m 16s
59:	learn: 0.1820237	total: 20.1s	remaining: 5m 15s
60:	learn: 0.1803333	total: 20.4s	remaining: 5m 14s
61:	learn: 0.1785862	total: 20.8s	remaining: 5m 15s
62:	learn: 0.1768835	total: 21.2s	remaining: 5m 15s
63:	learn: 0.1753903	total: 21.5s	remaining: 5m 15s
64:	learn: 0.1740193	total: 21.9s	remaining: 5m 14s
65:	learn: 0.1724734	total: 22.2s	remaining: 5m 14s
66:	learn: 0.1713189	total: 22.5s	remaining: 5m 13s
67:	learn: 0.1702051	total: 22.8s	remaining: 5m 12s
68:	learn: 0.1689400	total: 23.2s	remaining: 5m 12s
69:	learn: 0.1677637	total: 23.5s	remaining: 5m 11s
70:	learn: 0.1664594	total: 23.8s	remaining: 5m 11s
71:	learn: 0.1656988	total: 24.1s	remaining: 5m 10s
72:	learn: 0.1647031	total: 24.4s	remaining: 5m 9s
73:	learn: 0.1638027	total: 24.7s	remaining: 5m 9s
74:	learn: 0.1627019	total: 25.1s	remaining: 5m 8s
75:	learn: 0.1617550	total: 25.4s	remaining: 5m 8s
76:	learn: 0.1608385	total: 25.7s	remaining: 5m 8s
77:	learn: 0.1599193	total: 26s	remaining: 5m 7s
78:	learn: 0.1589137	total: 26.4s	remaining: 5m 7s
79:	learn: 0.1582104	total: 26.7s	remaining: 5m 7s
80:	learn: 0.1573160	total: 27s	remaining: 5m 6s
81:	learn: 0.1567457	total: 27.4s	remaining: 5m 6s
82:	learn: 0.1559580	total: 27.7s	remaining: 5m 6s
83:	learn: 0.1553205	total: 28s	remaining: 5m 5s
84:	learn: 0.1544086	total: 28.4s	remaining: 5m 5s
85:	learn: 0.1537522	total: 28.7s	remaining: 5m 4s
86:	learn: 0.1531781	total: 29s	remaining: 5m 4s
87:	learn: 0.1525189	total: 29.3s	remaining: 5m 3s
88:	learn: 0.1520091	total: 29.7s	remaining: 5m 3s
89:	learn: 0.1515603	total: 30s	remaining: 5m 3s
90:	learn: 0.1509659	total: 30.3s	remaining: 5m 3s
91:	learn: 0.1503596	total: 30.7s	remaining: 5m 2s
92:	learn: 0.1498109	total: 31s	remaining: 5m 2s
93:	learn: 0.1492427	total: 31.3s	remaining: 5m 2s
94:	learn: 0.1486150	total: 31.7s	remaining: 5m 1s
95:	learn: 0.1481951	total: 32s	remaining: 5m 1s
96:	learn: 0.1475973	total: 32.4s	remaining: 5m 1s
97:	learn: 0.1472314	total: 32.7s	remaining: 5m
98:	learn: 0.1467200	total: 33s	remaining: 5m
99:	learn: 0.1462395	total: 33.4s	remaining: 5m
100:	learn: 0.1457625	total: 33.7s	remaining: 4m 59s
101:	learn: 0.1453937	total: 34s	remaining: 4m 59s
102:	learn: 0.1450094	total: 34.4s	remaining: 4m 59s
103:	learn: 0.1444186	total: 34.7s	remaining: 4m 58s
104:	learn: 0.1441332	total: 35s	remaining: 4m 58s
105:	learn: 0.1437766	total: 35.4s	remaining: 4m 58s
106:	learn: 0.1432015	total: 35.7s	remaining: 4m 58s
107:	learn: 0.1428044	total: 36.1s	remaining: 4m 57s
108:	learn: 0.1422794	total: 36.4s	remaining: 4m 57s
109:	learn: 0.1418571	total: 36.7s	remaining: 4m 57s
110:	learn: 0.1414198	total: 37s	remaining: 4m 56s
111:	learn: 0.1411027	total: 37.4s	remaining: 4m 56s
112:	learn: 0.1406837	total: 37.7s	remaining: 4m 56s
113:	learn: 0.1403253	total: 38s	remaining: 4m 55s
114:	learn: 0.1399769	total: 38.4s	remaining: 4m 55s
115:	learn: 0.1394803	total: 38.7s	remaining: 4m 54s
116:	learn: 0.1392066	total: 39s	remaining: 4m 54s
117:	learn: 0.1388639	total: 39.3s	remaining: 4m 53s
118:	learn: 0.1385756	total: 39.7s	remaining: 4m 53s
119:	learn: 0.1383383	total: 40s	remaining: 4m 53s
120:	learn: 0.1380859	total: 40.3s	remaining: 4m 52s
121:	learn: 0.1376948	total: 40.6s	remaining: 4m 52s
122:	learn: 0.1375071	total: 40.9s	remaining: 4m 51s
123:	learn: 0.1372275	total: 41.2s	remaining: 4m 51s
124:	learn: 0.1368695	total: 41.6s	remaining: 4m 51s
125:	learn: 0.1365733	total: 41.9s	remaining: 4m 50s
126:	learn: 0.1362448	total: 42.2s	remaining: 4m 50s
127:	learn: 0.1360467	total: 42.6s	remaining: 4m 50s
128:	learn: 0.1357323	total: 42.9s	remaining: 4m 49s
129:	learn: 0.1355507	total: 43.3s	remaining: 4m 49s
130:	learn: 0.1352040	total: 43.6s	remaining: 4m 49s
131:	learn: 0.1349785	total: 43.9s	remaining: 4m 48s
132:	learn: 0.1348275	total: 44.3s	remaining: 4m 48s
133:	learn: 0.1346052	total: 44.6s	remaining: 4m 48s
134:	learn: 0.1344514	total: 44.9s	remaining: 4m 47s
135:	learn: 0.1341266	total: 45.2s	remaining: 4m 47s
136:	learn: 0.1339556	total: 45.6s	remaining: 4m 46s
137:	learn: 0.1337825	total: 45.9s	remaining: 4m 46s
138:	learn: 0.1336369	total: 46.2s	remaining: 4m 46s
139:	learn: 0.1333777	total: 46.6s	remaining: 4m 46s
140:	learn: 0.1331167	total: 46.9s	remaining: 4m 45s
141:	learn: 0.1329109	total: 47.2s	remaining: 4m 45s
142:	learn: 0.1325201	total: 47.6s	remaining: 4m 45s
143:	learn: 0.1321996	total: 47.9s	remaining: 4m 44s
144:	learn: 0.1319466	total: 48.2s	remaining: 4m 44s
145:	learn: 0.1317776	total: 48.6s	remaining: 4m 44s
146:	learn: 0.1315806	total: 48.9s	remaining: 4m 43s
147:	learn: 0.1313583	total: 49.2s	remaining: 4m 43s
148:	learn: 0.1311342	total: 49.6s	remaining: 4m 43s
149:	learn: 0.1308739	total: 49.9s	remaining: 4m 42s
150:	learn: 0.1306379	total: 50.2s	remaining: 4m 42s
151:	learn: 0.1305286	total: 50.5s	remaining: 4m 42s
152:	learn: 0.1303371	total: 50.9s	remaining: 4m 41s
153:	learn: 0.1299903	total: 51.2s	remaining: 4m 41s
154:	learn: 0.1299094	total: 51.6s	remaining: 4m 41s
155:	learn: 0.1297096	total: 51.9s	remaining: 4m 40s
156:	learn: 0.1295663	total: 52.3s	remaining: 4m 40s
157:	learn: 0.1293828	total: 52.6s	remaining: 4m 40s
158:	learn: 0.1292245	total: 52.9s	remaining: 4m 39s
159:	learn: 0.1290242	total: 53.3s	remaining: 4m 39s
160:	learn: 0.1288792	total: 53.6s	remaining: 4m 39s
161:	learn: 0.1287291	total: 54s	remaining: 4m 39s
162:	learn: 0.1285651	total: 54.3s	remaining: 4m 38s
163:	learn: 0.1284770	total: 54.7s	remaining: 4m 38s
164:	learn: 0.1282530	total: 55s	remaining: 4m 38s
165:	learn: 0.1281088	total: 55.3s	remaining: 4m 37s
166:	learn: 0.1280229	total: 55.6s	remaining: 4m 37s
167:	learn: 0.1278161	total: 55.9s	remaining: 4m 37s
168:	learn: 0.1275124	total: 56.3s	remaining: 4m 37s
169:	learn: 0.1273064	total: 56.7s	remaining: 4m 36s
170:	learn: 0.1271627	total: 57.1s	remaining: 4m 36s
171:	learn: 0.1269365	total: 57.4s	remaining: 4m 36s
172:	learn: 0.1267503	total: 57.7s	remaining: 4m 35s
173:	learn: 0.1266287	total: 58s	remaining: 4m 35s
174:	learn: 0.1264157	total: 58.4s	remaining: 4m 35s
175:	learn: 0.1261736	total: 58.7s	remaining: 4m 34s
176:	learn: 0.1260114	total: 59s	remaining: 4m 34s
177:	learn: 0.1258325	total: 59.4s	remaining: 4m 34s
178:	learn: 0.1256895	total: 59.7s	remaining: 4m 33s
179:	learn: 0.1254508	total: 1m	remaining: 4m 33s
180:	learn: 0.1253023	total: 1m	remaining: 4m 33s
181:	learn: 0.1251674	total: 1m	remaining: 4m 32s
182:	learn: 0.1250300	total: 1m 1s	remaining: 4m 32s
183:	learn: 0.1248617	total: 1m 1s	remaining: 4m 32s
184:	learn: 0.1246575	total: 1m 1s	remaining: 4m 31s
185:	learn: 0.1244868	total: 1m 2s	remaining: 4m 31s
186:	learn: 0.1243871	total: 1m 2s	remaining: 4m 31s
187:	learn: 0.1242349	total: 1m 2s	remaining: 4m 30s
188:	learn: 0.1241340	total: 1m 3s	remaining: 4m 30s
189:	learn: 0.1239957	total: 1m 3s	remaining: 4m 30s
190:	learn: 0.1238079	total: 1m 3s	remaining: 4m 29s
191:	learn: 0.1236979	total: 1m 4s	remaining: 4m 29s
192:	learn: 0.1235331	total: 1m 4s	remaining: 4m 29s
193:	learn: 0.1234137	total: 1m 4s	remaining: 4m 28s
194:	learn: 0.1232492	total: 1m 5s	remaining: 4m 28s
195:	learn: 0.1231046	total: 1m 5s	remaining: 4m 28s
196:	learn: 0.1230018	total: 1m 5s	remaining: 4m 27s
197:	learn: 0.1228264	total: 1m 6s	remaining: 4m 27s
198:	learn: 0.1226849	total: 1m 6s	remaining: 4m 27s
199:	learn: 0.1226032	total: 1m 6s	remaining: 4m 26s
200:	learn: 0.1224552	total: 1m 7s	remaining: 4m 26s
201:	learn: 0.1223339	total: 1m 7s	remaining: 4m 26s
202:	learn: 0.1222248	total: 1m 7s	remaining: 4m 26s
203:	learn: 0.1220669	total: 1m 8s	remaining: 4m 26s
204:	learn: 0.1219275	total: 1m 8s	remaining: 4m 25s
205:	learn: 0.1217610	total: 1m 8s	remaining: 4m 25s
206:	learn: 0.1216183	total: 1m 9s	remaining: 4m 24s
207:	learn: 0.1214109	total: 1m 9s	remaining: 4m 24s
208:	learn: 0.1213490	total: 1m 9s	remaining: 4m 24s
209:	learn: 0.1212203	total: 1m 10s	remaining: 4m 23s
210:	learn: 0.1211367	total: 1m 10s	remaining: 4m 23s
211:	learn: 0.1209903	total: 1m 10s	remaining: 4m 23s
212:	learn: 0.1209335	total: 1m 11s	remaining: 4m 22s
213:	learn: 0.1207892	total: 1m 11s	remaining: 4m 22s
214:	learn: 0.1206609	total: 1m 11s	remaining: 4m 22s
215:	learn: 0.1205619	total: 1m 12s	remaining: 4m 21s
216:	learn: 0.1204391	total: 1m 12s	remaining: 4m 21s
217:	learn: 0.1203237	total: 1m 12s	remaining: 4m 21s
218:	learn: 0.1201158	total: 1m 13s	remaining: 4m 20s
219:	learn: 0.1200571	total: 1m 13s	remaining: 4m 20s
220:	learn: 0.1199822	total: 1m 13s	remaining: 4m 20s
221:	learn: 0.1198888	total: 1m 14s	remaining: 4m 19s
222:	learn: 0.1197910	total: 1m 14s	remaining: 4m 19s
223:	learn: 0.1196263	total: 1m 14s	remaining: 4m 18s
224:	learn: 0.1194711	total: 1m 15s	remaining: 4m 18s
225:	learn: 0.1194324	total: 1m 15s	remaining: 4m 18s
226:	learn: 0.1193849	total: 1m 15s	remaining: 4m 17s
227:	learn: 0.1192866	total: 1m 16s	remaining: 4m 17s
228:	learn: 0.1192196	total: 1m 16s	remaining: 4m 17s
229:	learn: 0.1190775	total: 1m 16s	remaining: 4m 16s
230:	learn: 0.1189423	total: 1m 17s	remaining: 4m 16s
231:	learn: 0.1188601	total: 1m 17s	remaining: 4m 16s
232:	learn: 0.1188121	total: 1m 17s	remaining: 4m 15s
233:	learn: 0.1186832	total: 1m 18s	remaining: 4m 15s
234:	learn: 0.1185269	total: 1m 18s	remaining: 4m 15s
235:	learn: 0.1184461	total: 1m 18s	remaining: 4m 14s
236:	learn: 0.1183496	total: 1m 19s	remaining: 4m 14s
237:	learn: 0.1182630	total: 1m 19s	remaining: 4m 14s
238:	learn: 0.1181980	total: 1m 19s	remaining: 4m 13s
239:	learn: 0.1181169	total: 1m 20s	remaining: 4m 13s
240:	learn: 0.1180120	total: 1m 20s	remaining: 4m 12s
241:	learn: 0.1178646	total: 1m 20s	remaining: 4m 12s
242:	learn: 0.1178187	total: 1m 20s	remaining: 4m 12s
243:	learn: 0.1176733	total: 1m 21s	remaining: 4m 11s
244:	learn: 0.1175982	total: 1m 21s	remaining: 4m 11s
245:	learn: 0.1174789	total: 1m 21s	remaining: 4m 11s
246:	learn: 0.1173556	total: 1m 22s	remaining: 4m 10s
247:	learn: 0.1172534	total: 1m 22s	remaining: 4m 10s
248:	learn: 0.1171416	total: 1m 22s	remaining: 4m 10s
249:	learn: 0.1169807	total: 1m 23s	remaining: 4m 9s
250:	learn: 0.1168860	total: 1m 23s	remaining: 4m 9s
251:	learn: 0.1167502	total: 1m 23s	remaining: 4m 9s
252:	learn: 0.1166957	total: 1m 24s	remaining: 4m 8s
253:	learn: 0.1165883	total: 1m 24s	remaining: 4m 8s
254:	learn: 0.1164826	total: 1m 24s	remaining: 4m 8s
255:	learn: 0.1163820	total: 1m 25s	remaining: 4m 7s
256:	learn: 0.1163066	total: 1m 25s	remaining: 4m 7s
257:	learn: 0.1162055	total: 1m 25s	remaining: 4m 7s
258:	learn: 0.1160695	total: 1m 26s	remaining: 4m 6s
259:	learn: 0.1159132	total: 1m 26s	remaining: 4m 6s
260:	learn: 0.1158158	total: 1m 27s	remaining: 4m 6s
261:	learn: 0.1157338	total: 1m 27s	remaining: 4m 6s
262:	learn: 0.1157118	total: 1m 27s	remaining: 4m 5s
263:	learn: 0.1156112	total: 1m 27s	remaining: 4m 5s
264:	learn: 0.1155068	total: 1m 28s	remaining: 4m 4s
265:	learn: 0.1154130	total: 1m 28s	remaining: 4m 4s
266:	learn: 0.1153196	total: 1m 28s	remaining: 4m 4s
267:	learn: 0.1151608	total: 1m 29s	remaining: 4m 3s
268:	learn: 0.1150851	total: 1m 29s	remaining: 4m 3s
269:	learn: 0.1150074	total: 1m 29s	remaining: 4m 3s
270:	learn: 0.1149265	total: 1m 30s	remaining: 4m 2s
271:	learn: 0.1147271	total: 1m 30s	remaining: 4m 2s
272:	learn: 0.1146890	total: 1m 30s	remaining: 4m 2s
273:	learn: 0.1146640	total: 1m 31s	remaining: 4m 1s
274:	learn: 0.1146414	total: 1m 31s	remaining: 4m 1s
275:	learn: 0.1145903	total: 1m 31s	remaining: 4m 1s
276:	learn: 0.1145177	total: 1m 32s	remaining: 4m
277:	learn: 0.1144364	total: 1m 32s	remaining: 4m
278:	learn: 0.1143727	total: 1m 32s	remaining: 4m
279:	learn: 0.1142844	total: 1m 33s	remaining: 3m 59s
280:	learn: 0.1142146	total: 1m 33s	remaining: 3m 59s
281:	learn: 0.1141506	total: 1m 33s	remaining: 3m 59s
282:	learn: 0.1140203	total: 1m 34s	remaining: 3m 58s
283:	learn: 0.1139373	total: 1m 34s	remaining: 3m 58s
284:	learn: 0.1138805	total: 1m 34s	remaining: 3m 58s
285:	learn: 0.1138055	total: 1m 35s	remaining: 3m 57s
286:	learn: 0.1137151	total: 1m 35s	remaining: 3m 57s
287:	learn: 0.1136199	total: 1m 35s	remaining: 3m 57s
288:	learn: 0.1135465	total: 1m 36s	remaining: 3m 56s
289:	learn: 0.1134790	total: 1m 36s	remaining: 3m 56s
290:	learn: 0.1133720	total: 1m 36s	remaining: 3m 56s
291:	learn: 0.1132707	total: 1m 37s	remaining: 3m 55s
292:	learn: 0.1131846	total: 1m 37s	remaining: 3m 55s
293:	learn: 0.1131144	total: 1m 37s	remaining: 3m 55s
294:	learn: 0.1130000	total: 1m 38s	remaining: 3m 54s
295:	learn: 0.1129428	total: 1m 38s	remaining: 3m 54s
296:	learn: 0.1128942	total: 1m 38s	remaining: 3m 54s
297:	learn: 0.1128094	total: 1m 39s	remaining: 3m 54s
298:	learn: 0.1127345	total: 1m 39s	remaining: 3m 53s
299:	learn: 0.1126911	total: 1m 40s	remaining: 3m 53s
300:	learn: 0.1125703	total: 1m 40s	remaining: 3m 53s
301:	learn: 0.1124814	total: 1m 40s	remaining: 3m 52s
302:	learn: 0.1123635	total: 1m 41s	remaining: 3m 52s
303:	learn: 0.1122849	total: 1m 41s	remaining: 3m 52s
304:	learn: 0.1122205	total: 1m 41s	remaining: 3m 51s
305:	learn: 0.1121838	total: 1m 42s	remaining: 3m 51s
306:	learn: 0.1121118	total: 1m 42s	remaining: 3m 51s
307:	learn: 0.1120649	total: 1m 42s	remaining: 3m 50s
308:	learn: 0.1120157	total: 1m 43s	remaining: 3m 50s
309:	learn: 0.1119612	total: 1m 43s	remaining: 3m 50s
310:	learn: 0.1118991	total: 1m 43s	remaining: 3m 49s
311:	learn: 0.1117514	total: 1m 44s	remaining: 3m 49s
312:	learn: 0.1116780	total: 1m 44s	remaining: 3m 49s
313:	learn: 0.1116404	total: 1m 44s	remaining: 3m 48s
314:	learn: 0.1115336	total: 1m 44s	remaining: 3m 48s
315:	learn: 0.1114053	total: 1m 45s	remaining: 3m 47s
316:	learn: 0.1113367	total: 1m 45s	remaining: 3m 47s
317:	learn: 0.1112026	total: 1m 45s	remaining: 3m 47s
318:	learn: 0.1111673	total: 1m 46s	remaining: 3m 46s
319:	learn: 0.1110819	total: 1m 46s	remaining: 3m 46s
320:	learn: 0.1110167	total: 1m 46s	remaining: 3m 46s
321:	learn: 0.1109568	total: 1m 47s	remaining: 3m 45s
322:	learn: 0.1108985	total: 1m 47s	remaining: 3m 45s
323:	learn: 0.1108610	total: 1m 47s	remaining: 3m 45s
324:	learn: 0.1108011	total: 1m 48s	remaining: 3m 44s
325:	learn: 0.1107427	total: 1m 48s	remaining: 3m 44s
326:	learn: 0.1106976	total: 1m 48s	remaining: 3m 44s
327:	learn: 0.1106500	total: 1m 49s	remaining: 3m 43s
328:	learn: 0.1105513	total: 1m 49s	remaining: 3m 43s
329:	learn: 0.1104975	total: 1m 49s	remaining: 3m 43s
330:	learn: 0.1104214	total: 1m 50s	remaining: 3m 42s
331:	learn: 0.1103789	total: 1m 50s	remaining: 3m 42s
332:	learn: 0.1102613	total: 1m 50s	remaining: 3m 42s
333:	learn: 0.1101371	total: 1m 51s	remaining: 3m 41s
334:	learn: 0.1100639	total: 1m 51s	remaining: 3m 41s
335:	learn: 0.1100159	total: 1m 51s	remaining: 3m 41s
336:	learn: 0.1099356	total: 1m 52s	remaining: 3m 40s
337:	learn: 0.1098638	total: 1m 52s	remaining: 3m 40s
338:	learn: 0.1097898	total: 1m 52s	remaining: 3m 40s
339:	learn: 0.1097343	total: 1m 53s	remaining: 3m 39s
340:	learn: 0.1096927	total: 1m 53s	remaining: 3m 39s
341:	learn: 0.1096535	total: 1m 53s	remaining: 3m 39s
342:	learn: 0.1095232	total: 1m 54s	remaining: 3m 38s
343:	learn: 0.1094470	total: 1m 54s	remaining: 3m 38s
344:	learn: 0.1094011	total: 1m 54s	remaining: 3m 38s
345:	learn: 0.1093259	total: 1m 55s	remaining: 3m 37s
346:	learn: 0.1092894	total: 1m 55s	remaining: 3m 37s
347:	learn: 0.1092523	total: 1m 55s	remaining: 3m 37s
348:	learn: 0.1091582	total: 1m 56s	remaining: 3m 36s
349:	learn: 0.1091250	total: 1m 56s	remaining: 3m 36s
350:	learn: 0.1090526	total: 1m 56s	remaining: 3m 36s
351:	learn: 0.1090014	total: 1m 57s	remaining: 3m 35s
352:	learn: 0.1089412	total: 1m 57s	remaining: 3m 35s
353:	learn: 0.1088936	total: 1m 57s	remaining: 3m 35s
354:	learn: 0.1087941	total: 1m 58s	remaining: 3m 34s
355:	learn: 0.1087426	total: 1m 58s	remaining: 3m 34s
356:	learn: 0.1087045	total: 1m 58s	remaining: 3m 34s
357:	learn: 0.1086503	total: 1m 59s	remaining: 3m 33s
358:	learn: 0.1085967	total: 1m 59s	remaining: 3m 33s
359:	learn: 0.1085200	total: 1m 59s	remaining: 3m 33s
360:	learn: 0.1084653	total: 2m	remaining: 3m 32s
361:	learn: 0.1084481	total: 2m	remaining: 3m 32s
362:	learn: 0.1084315	total: 2m	remaining: 3m 32s
363:	learn: 0.1083955	total: 2m 1s	remaining: 3m 31s
364:	learn: 0.1083624	total: 2m 1s	remaining: 3m 31s
365:	learn: 0.1083102	total: 2m 1s	remaining: 3m 31s
366:	learn: 0.1082409	total: 2m 2s	remaining: 3m 30s
367:	learn: 0.1081600	total: 2m 2s	remaining: 3m 30s
368:	learn: 0.1081155	total: 2m 2s	remaining: 3m 30s
369:	learn: 0.1080667	total: 2m 3s	remaining: 3m 29s
370:	learn: 0.1080157	total: 2m 3s	remaining: 3m 29s
371:	learn: 0.1079646	total: 2m 3s	remaining: 3m 29s
372:	learn: 0.1079122	total: 2m 4s	remaining: 3m 28s
373:	learn: 0.1078433	total: 2m 4s	remaining: 3m 28s
374:	learn: 0.1077925	total: 2m 4s	remaining: 3m 28s
375:	learn: 0.1077379	total: 2m 5s	remaining: 3m 27s
376:	learn: 0.1076962	total: 2m 5s	remaining: 3m 27s
377:	learn: 0.1076546	total: 2m 5s	remaining: 3m 27s
378:	learn: 0.1076106	total: 2m 6s	remaining: 3m 27s

In [13]:
model_v2 = CatBoostClassifier(
    iterations=1000,
    learning_rate=0.05,
    depth=8,
    verbose=0
)

model_v2.fit(
    X,
    y,
    cat_features=["spectral_type", "galaxy_population"]
)

CatBoostClassifier(depth=8, iterations=1000, learning_rate=0.05, verbose=0)

In [14]:
model_v2.save_model("../models/catboost_v2.cbm")

In [15]:
X_test = test.drop(columns=["id"])

preds = model_v2.predict(X_test)

submission = pd.DataFrame({
    "id": test["id"],
    "class": preds.flatten()
})

submission.to_csv(
    "../submissions/submission_v2.csv",
    index=False
)

# ==================================
# Experiment V3
# Feature Engineering
# ==================================

In [16]:
X_fe = X.copy()
X_test_fe = test.drop(columns=["id"]).copy()

In [17]:
X_fe["u_g"] = X_fe["u"] - X_fe["g"]
X_fe["g_r"] = X_fe["g"] - X_fe["r"]
X_fe["r_i"] = X_fe["r"] - X_fe["i"]
X_fe["i_z"] = X_fe["i"] - X_fe["z"]

In [18]:
X_test_fe["u_g"] = X_test_fe["u"] - X_test_fe["g"]
X_test_fe["g_r"] = X_test_fe["g"] - X_test_fe["r"]
X_test_fe["r_i"] = X_test_fe["r"] - X_test_fe["i"]
X_test_fe["i_z"] = X_test_fe["i"] - X_test_fe["z"]

In [19]:
print(X_fe.columns)

Index(['alpha', 'delta', 'u', 'g', 'r', 'i', 'z', 'redshift', 'spectral_type',
       'galaxy_population', 'u_g', 'g_r', 'r_i', 'i_z'],
      dtype='str')

In [22]:
skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

scores = []

for train_idx, valid_idx in skf.split(X_fe, y):

    X_train = X_fe.iloc[train_idx]
    X_valid = X_fe.iloc[valid_idx]

    y_train = y.iloc[train_idx]
    y_valid = y.iloc[valid_idx]

    model = CatBoostClassifier(
        iterations=1000,
        learning_rate=0.05,
        depth=8,
        verbose=0
    )

    model.fit(
        X_train,
        y_train,
        cat_features=["spectral_type", "galaxy_population"]
    )

    preds = model.predict(X_valid)

    score = balanced_accuracy_score(y_valid, preds)

    scores.append(score)

    print(f"Fold Score: {score:.6f}")

print("\nMean CV Score:", np.mean(scores))

Fold Score: 0.949647
Fold Score: 0.951436
Fold Score: 0.949838
Fold Score: 0.950853
Fold Score: 0.950572

Mean CV Score: 0.9504691423379971

In [23]:
model_v3 = CatBoostClassifier(
    iterations=1000,
    learning_rate=0.05,
    depth=8,
    verbose=0
)

model_v3.fit(
    X_fe,
    y,
    cat_features=["spectral_type", "galaxy_population"]
)

CatBoostClassifier(depth=8, iterations=1000, learning_rate=0.05, verbose=0)

In [24]:
preds = model_v3.predict(X_test_fe)

submission = pd.DataFrame({
    "id": test["id"],
    "class": preds.flatten()
})

submission.to_csv(
    "../submissions/submission_v3.csv",
    index=False
)

In [25]:
model_v3.save_model("../models/catboost_v3.cbm")

### Next Experiment (V4)

let's add a few more astronomy-inspired features.

In [26]:
X_fe["u_r"] = X_fe["u"] - X_fe["r"]
X_fe["g_i"] = X_fe["g"] - X_fe["i"]
X_fe["r_z"] = X_fe["r"] - X_fe["z"]

In [27]:
X_test_fe["u_r"] = X_test_fe["u"] - X_test_fe["r"]
X_test_fe["g_i"] = X_test_fe["g"] - X_test_fe["i"]
X_test_fe["r_z"] = X_test_fe["r"] - X_test_fe["z"]

In [28]:
print(X_fe.columns)

Index(['alpha', 'delta', 'u', 'g', 'r', 'i', 'z', 'redshift', 'spectral_type',
       'galaxy_population', 'u_g', 'g_r', 'r_i', 'i_z', 'u_r', 'g_i', 'r_z'],
      dtype='str')

In [29]:
skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

scores = []

for train_idx, valid_idx in skf.split(X_fe, y):

    X_train = X_fe.iloc[train_idx]
    X_valid = X_fe.iloc[valid_idx]

    y_train = y.iloc[train_idx]
    y_valid = y.iloc[valid_idx]

    model = CatBoostClassifier(
        iterations=1000,
        learning_rate=0.05,
        depth=8,
        verbose=0
    )

    model.fit(
        X_train,
        y_train,
        cat_features=["spectral_type", "galaxy_population"]
    )

    preds = model.predict(X_valid)

    score = balanced_accuracy_score(y_valid, preds)

    scores.append(score)

    print(f"Fold Score: {score:.6f}")

print("\nMean CV Score:", np.mean(scores))

Fold Score: 0.950009
Fold Score: 0.951617
Fold Score: 0.950912
Fold Score: 0.951151
Fold Score: 0.951626

Mean CV Score: 0.9510631811088202

In [30]:
model_v4 = CatBoostClassifier(
    iterations=1000,
    learning_rate=0.05,
    depth=8,
    verbose=0
)

model_v4.fit(
    X_fe,
    y,
    cat_features=["spectral_type", "galaxy_population"]
)

CatBoostClassifier(depth=8, iterations=1000, learning_rate=0.05, verbose=0)

In [31]:
model_v4.save_model("../models/catboost_v4.cbm")

In [32]:
preds = model_v4.predict(X_test_fe)

submission = pd.DataFrame({
    "id": test["id"],
    "class": preds.flatten()
})

submission.to_csv(
    "../submissions/submission_v4.csv",
    index=False
)

### Experiment V5: Feature Importance on V4

In [33]:
feature_importance = pd.DataFrame({
    "Feature": X_fe.columns,
    "Importance": model_v4.get_feature_importance()
})

feature_importance.sort_values(
    by="Importance",
    ascending=False
)

              Feature  Importance
7            redshift   34.785292
0               alpha   10.523213
15                g_i    8.789111
1               delta    8.481540
6                   z    5.996740
16                r_z    5.134568
14                u_r    4.046187
10                u_g    3.883111
3                   g    3.423199
2                   u    3.408275
5                   i    3.087655
4                   r    2.602107
11                g_r    2.551325
13                i_z    1.313911
12                r_i    1.116059
8       spectral_type    0.592126
9   galaxy_population    0.265582

## Surprising Discovery #1

Look at:

spectral_type    :   0.59

galaxy_population :  0.27

These are almost useless now.

Initially they seemed important, but after feature engineering CatBoost is extracting the same information from the numerical features.

This is a good example of why we check feature importance instead of making assumptions.

## Surprising Discovery #2

Your engineered features are working!

g_i  = 8.79

r_z  = 5.13

u_r  = 4.05

u_g  = 3.88

Some of these are more important than the original magnitude features.

That's exactly why your leaderboard score increased.

# Experiment V5 (High Value)

Let's test whether those two categorical columns are still needed.

In [34]:
X_v5 = X_fe.drop(
    columns=["spectral_type", "galaxy_population"]
)

X_test_v5 = X_test_fe.drop(
    columns=["spectral_type", "galaxy_population"]
)

In [36]:
print(X_v5.columns)

Index(['alpha', 'delta', 'u', 'g', 'r', 'i', 'z', 'redshift', 'u_g', 'g_r',
       'r_i', 'i_z', 'u_r', 'g_i', 'r_z'],
      dtype='str')

In [38]:
skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

scores = []

for train_idx, valid_idx in skf.split(X_v5, y):

    X_train = X_v5.iloc[train_idx]
    X_valid = X_v5.iloc[valid_idx]

    y_train = y.iloc[train_idx]
    y_valid = y.iloc[valid_idx]

    model = CatBoostClassifier(
        iterations=1000,
        learning_rate=0.05,
        depth=8,
        verbose=0
    )

    model.fit(
        X_train,
        y_train,
        # cat_features=["spectral_type", "galaxy_population"]
    )

    preds = model.predict(X_valid)

    score = balanced_accuracy_score(y_valid, preds)

    scores.append(score)

    print(f"Fold Score: {score:.6f}")

print("\nMean CV Score:", np.mean(scores))

Fold Score: 0.949848
Fold Score: 0.952363
Fold Score: 0.950895
Fold Score: 0.951659
Fold Score: 0.951220

Mean CV Score: 0.9511968978771405

In [40]:
model_v5 = CatBoostClassifier(
    iterations=1000,
    learning_rate=0.05,
    depth=8,
    verbose=0
)

model_v5.fit(
    X_v5,
    y,
    # cat_features=["spectral_type", "galaxy_population"]
)

CatBoostClassifier(depth=8, iterations=1000, learning_rate=0.05, verbose=0)

In [41]:
model_v5.save_model("../models/catboost_v5.cbm")

In [42]:
preds = model_v5.predict(X_test_v5)

submission = pd.DataFrame({
    "id": test["id"],
    "class": preds.flatten()
})

submission.to_csv(
    "../submissions/submission_v5.csv",
    index=False
)